### ISSUE TITLE
[BUG]For unofficial custom npc mod, armor cannot be displayed normally

### ISSUE THREAD

**Issue by Xall0y** [RiskyKen/Armourers-Workshop#495]
**Describe the bug**
1.20.1 and the latest version of unofficial custom npc mod,Armor often does not show.

**To Reproduce**
1. Sometimes, when I first entered save, armor can be displayed on npc.
2. But after that, all armor will not be displayed, except weapons.

**Expected behavior**
I'd appreciate it if you could fix this!

**Screenshots**
![2024-12-14_10 07 54](https://github.com/user-attachments/assets/9661f7fc-2f1e-4095-baae-e1471809c60c)

**Debug crash log**
[report-2024-12-14_10.16.39.zip](https://github.com/user-attachments/files/18133939/report-2024-12-14_10.16.39.zip)

**Additional context**
Once, I summoned another npc next to an npc that normally displayed armor, and then all npc's armor was not displayed.

**Comment by SAGESSE-CN** [comment]
fixed, but it will release in next version

**Comment by Xall0y** [comment]
thanks!

**Comment by Xall0y** [comment]
hello!I found that the problem still exists, but it seems that as long as I use the unofficial custom npc mod to create an npc using the warden model,then all armor will be invisible.by the way,my version is still 1.20.1forge
